# Generated by Django 4.0.4 on 2022-08-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
